"""Email transport helpers for simulation harness runs."""

from __future__ import annotations

import base64
import mailbox
import os
import re
from collections import defaultdict
from collections.abc import Awaitable, Callable, Iterable, Iterator
from contextlib import contextmanager
from copy import deepcopy
from dataclasses import dataclass, field
from email import policy
from email.message import EmailMessage
from email.parser import BytesParser
from email.utils import getaddresses, parseaddr
from pathlib import Path
from typing import Any
from unittest.mock import patch
from uuid import uuid4

from thenetwork.email.inbound import cap_body, cap_sender_name, cap_subject
from thenetwork.email.relay import is_relay_address_candidate
from thenetwork.email.threading import clean_message_id, clean_references
from thenetwork.security.log_redaction import redact_structured_log
from thenetwork.settings import get_settings
from thenetwork.sim.html_validation import html_to_visible_text
from thenetwork.worker.tasks import process_email


ProcessEmailCallable = Callable[..., Awaitable[None]]
SimMessageObserver = Callable[[EmailMessage, "SimMessageMeta | None"], None]

# These headers are regenerated by ``set_content`` or contain only MIME framing
# after ``_redact_message`` replaces multipart boundaries. Message identifier
# headers are separately replaced with RFC-valid opaque identifiers. Every other
# header is mail content and must pass through the log redactor before a public
# mbox is written.
_SAFE_MIME_HEADERS = frozenset(
    {"content-transfer-encoding", "content-type", "mime-version"}
)
_MESSAGE_IDENTIFIER_HEADERS = frozenset(
    {
        "content-id",
        "in-reply-to",
        "message-id",
        "references",
        "resent-message-id",
    }
)
_SINGLE_MESSAGE_IDENTIFIER_HEADERS = frozenset(
    {"content-id", "message-id", "resent-message-id"}
)
_MESSAGE_IDENTIFIER_PATTERN = re.compile(r"<[^<>\r\n]+>")
_SAFE_TEXT_SUBTYPES = frozenset({"html", "plain"})
_SAFE_MULTIPART_SUBTYPES = frozenset({"alternative", "mixed"})


@dataclass(frozen=True)
class SimMessageMeta:
    """Metadata stamped onto every sim-delivered message."""

    tick: int
    direction: str
    persona: str
    trace_id: str


@dataclass
class SimPostOffice:
    """In-memory mailbox keyed by normalized recipient address."""

    mbox_path: Path | None = None
    on_deliver: SimMessageObserver | None = None
    _messages: dict[str, list[EmailMessage]] = field(
        default_factory=lambda: defaultdict(list)
    )

    def deliver(
        self, message: EmailMessage, meta: SimMessageMeta | None = None
    ) -> None:
        message = deepcopy(message)
        if meta is not None:
            _stamp_sim_headers(message, meta)
        if self.on_deliver is not None:
            self.on_deliver(message, meta)
        self._append_to_mbox(message)
        recipients = _recipient_addresses(message)
        if not recipients:
            return
        for recipient in recipients:
            self._messages[recipient].append(deepcopy(message))

    def messages_for(self, address: str) -> tuple[EmailMessage, ...]:
        return tuple(self._messages.get(_normalize_address(address), ()))

    def pop_all(self, address: str) -> tuple[EmailMessage, ...]:
        return tuple(self._messages.pop(_normalize_address(address), ()))

    def requeue(self, address: str, messages: Iterable[EmailMessage]) -> None:
        """Put already-delivered messages back at the head of a queue.

        Used by the tick loop to hold extra consent threads for later turns.
        No mbox append happens here - the messages were logged on delivery.
        """
        held = [deepcopy(message) for message in messages]
        if not held:
            return
        self._messages[_normalize_address(address)][:0] = held

    @property
    def all_messages(self) -> tuple[EmailMessage, ...]:
        messages: list[EmailMessage] = []
        for bucket in self._messages.values():
            messages.extend(bucket)
        return tuple(messages)

    def _append_to_mbox(self, message: EmailMessage) -> None:
        if self.mbox_path is None:
            return
        self.mbox_path.parent.mkdir(parents=True, exist_ok=True)
        box = mailbox.mbox(self.mbox_path)
        try:
            box.lock()
            box.add(message)
            box.flush()
        finally:
            box.unlock()
            box.close()


def publish_redacted_mbox(raw_mbox_path: Path, public_mbox_path: Path) -> None:
    """Copy a private simulation mbox to its redacted, publishable counterpart."""
    raw_box = mailbox.mbox(raw_mbox_path)
    public_mbox_path.parent.mkdir(parents=True, exist_ok=True)
    public_box = mailbox.mbox(public_mbox_path, create=True)
    message_identifiers: dict[str, str] = {}
    try:
        public_box.lock()
        public_box.clear()
        for message in raw_box:
            # ``mailbox`` returns legacy ``Message`` subclasses. Reparse into
            # an ``EmailMessage`` so text and attachment payloads can be safely
            # replaced before the public mbox is serialized.
            redacted = BytesParser(policy=policy.default).parsebytes(message.as_bytes())
            _redact_message(redacted, message_identifiers)
            published = mailbox.mboxMessage(redacted)
            # mbox envelope senders are serialized separately from RFC-822
            # headers, so they require an explicit replacement as well.
            published.set_from("MAILER-DAEMON")
            public_box.add(published)
        public_box.flush()
    finally:
        public_box.unlock()
        public_box.close()
        raw_box.close()
    os.chmod(public_mbox_path, 0o600)


def _redact_message(message: EmailMessage, message_identifiers: dict[str, str]) -> None:
    for index, part in enumerate(message.walk()):
        if part.is_multipart():
            # Mailbox boundary values originate with the message sender.  A
            # fresh deterministic value preserves the safe multipart shape
            # without publishing an arbitrary raw header parameter. Keep an
            # alternative wrapper so public fixtures can still prove order.
            subtype = part.get_content_subtype()
            safe_subtype = subtype if subtype in _SAFE_MULTIPART_SUBTYPES else "mixed"
            del part["Content-Type"]
            part["Content-Type"] = f"multipart/{safe_subtype}"
            part.set_boundary(f"sim-redacted-{index}")
            _normalize_mime_headers(part)
            _redact_headers(part, message_identifiers)
            continue
        if part.get_content_maintype() == "text":
            try:
                content = part.get_content()
            except Exception:
                redacted = "[redaction-unavailable]"
            else:
                # Free-form bodies are all untrusted, including strings an
                # entity recognizer cannot classify. Preserve their shape and
                # approximate diagnostic value without publishing content.
                redacted = f"[redacted-text chars={len(content)}]"
            part.set_content(
                redacted,
                subtype=(
                    part.get_content_subtype()
                    if part.get_content_subtype() in _SAFE_TEXT_SUBTYPES
                    else "plain"
                ),
                charset=part.get_content_charset() or "utf-8",
            )
        else:
            # A binary part can contain arbitrary PII and cannot be safely
            # transformed as text.  Publish its existence, never its bytes.
            part.set_content("[non-text attachment omitted]")
        _normalize_mime_headers(part)
        _redact_headers(part, message_identifiers)


def _opaque_message_identifiers(
    value: str, message_identifiers: dict[str, str], *, single: bool
) -> str | None:
    """Replace RFC message identifiers without exposing or hashing their source."""
    source_identifiers = _MESSAGE_IDENTIFIER_PATTERN.findall(value)
    if single:
        source_identifiers = source_identifiers[:1]
    if not source_identifiers:
        return None

    opaque_identifiers: list[str] = []
    for source_identifier in source_identifiers:
        opaque_identifier = message_identifiers.get(source_identifier)
        if opaque_identifier is None:
            opaque_identifier = (
                f"<sim-redacted-{len(message_identifiers) + 1}@simulation.invalid>"
            )
            message_identifiers[source_identifier] = opaque_identifier
        opaque_identifiers.append(opaque_identifier)
    return " ".join(opaque_identifiers)


def _redact_headers(message: EmailMessage, message_identifiers: dict[str, str]) -> None:
    """Redact all non-MIME header values, including repeated custom headers."""
    for name in tuple(message.keys()):
        normalized_name = name.lower()
        if normalized_name in _SAFE_MIME_HEADERS:
            continue
        values = message.get_all(name, ())
        del message[name]
        for value in values:
            if normalized_name in _MESSAGE_IDENTIFIER_HEADERS:
                redacted_identifier = _opaque_message_identifiers(
                    str(value),
                    message_identifiers,
                    single=normalized_name in _SINGLE_MESSAGE_IDENTIFIER_HEADERS,
                )
                if redacted_identifier is not None:
                    message[name] = redacted_identifier
                continue
            redacted = redact_structured_log(value)
            message[name] = (
                redacted if isinstance(redacted, str) else "[redaction-unavailable]"
            )


def _normalize_mime_headers(message: EmailMessage) -> None:
    """Keep only generated MIME framing values in a published message."""
    if "MIME-Version" in message:
        message.replace_header("MIME-Version", "1.0")
    if "Content-Transfer-Encoding" in message and message.is_multipart():
        del message["Content-Transfer-Encoding"]


class _PostOfficeSMTP:
    def __init__(
        self,
        post_office: SimPostOffice,
        default_meta: SimMessageMeta | None = None,
    ) -> None:
        self.post_office = post_office
        self.default_meta = default_meta

    def __call__(self, *_args: Any, **_kwargs: Any) -> "_PostOfficeSMTP":
        return self

    def __enter__(self) -> "_PostOfficeSMTP":
        return self

    def __exit__(self, *_args: Any) -> bool:
        return False

    def ehlo(self) -> None:
        return None

    def starttls(self) -> None:
        return None

    def login(self, *_args: Any, **_kwargs: Any) -> None:
        return None

    def send_message(self, message: EmailMessage) -> None:
        self.post_office.deliver(message, self.default_meta)


@contextmanager
def capture_outbound(
    post_office: SimPostOffice,
    meta: SimMessageMeta | None = None,
) -> Iterator[SimPostOffice]:
    """Capture outbound mail produced by `thenetwork.email.outbound.send_reply`.

    The seam is deliberately the `smtplib.SMTP` object used inside
    `email/outbound.py`, so subject handling, threading headers, growth footer,
    Message-ID, Date, and Auto-Submitted are still composed by production code.
    IMAP Sent append is disabled because the post office is the run's mail log.
    """
    smtp = _PostOfficeSMTP(post_office, meta)
    with (
        patch("thenetwork.email.outbound.smtplib.SMTP", smtp),
        patch("thenetwork.email.outbound._append_to_sent", return_value=None),
    ):
        yield post_office


@dataclass(frozen=True)
class InboundDelivery:
    sender_email: str
    recipient_address: str | None
    subject: str
    body: str
    trace_id: str
    message_id: str | None


async def deliver_inbound(
    message: EmailMessage,
    *,
    sender_authenticated: bool = True,
    process: ProcessEmailCallable | None = None,
    trace_id: str | None = None,
    post_office: SimPostOffice | None = None,
    tick: int | None = None,
    persona: str | None = None,
) -> InboundDelivery:
    """Call the worker's `process_email` task directly for one EmailMessage."""
    sender_display_name, sender_email = parseaddr(message.get("From", ""))
    sender_email = sender_email.strip()
    if not sender_email:
        raise ValueError("inbound message must have a From address")

    subject = cap_subject(message.get("Subject", ""))
    body = cap_body(_extract_body(message))
    message_id = clean_message_id(message.get("Message-ID"))
    references = clean_references(message.get("References"))
    message_date = message.get("Date")
    resolved_trace_id = trace_id or str(uuid4())
    recipients = _recipient_addresses(message)
    recipient_address = recipients[0] if recipients else None
    raw_message_b64 = (
        base64.b64encode(message.as_bytes()).decode("ascii")
        if subject.strip().lower().startswith("admin:")
        or is_relay_address_candidate(recipient_address, get_settings().relay_domain)
        else None
    )
    process_func = process or process_email.func
    if post_office is not None:
        post_office.deliver(
            message,
            SimMessageMeta(
                tick=tick or 0,
                direction="persona->agent",
                persona=persona or sender_display_name or sender_email,
                trace_id=resolved_trace_id,
            ),
        )

    await process_func(
        sender_email=sender_email,
        subject=subject,
        body=body,
        sender_authenticated=sender_authenticated,
        sender_display_name=cap_sender_name(sender_display_name),
        recipient_address=recipient_address,
        raw_message_b64=raw_message_b64,
        inbound_message_id=message_id,
        inbound_references=references,
        inbound_body_for_quote=body,
        inbound_date=message_date,
        trace_id=resolved_trace_id,
    )

    return InboundDelivery(
        sender_email=sender_email,
        recipient_address=recipient_address,
        subject=subject,
        body=body,
        trace_id=resolved_trace_id,
        message_id=message_id,
    )


def render_transcript(
    mbox_path: Path,
    transcript_path: Path | None = None,
) -> str:
    """Render a compact Markdown transcript from a sim mbox."""
    box = mailbox.mbox(mbox_path)
    try:
        messages = list(box)
    finally:
        box.close()

    lines = ["# Simulation Transcript", ""]
    for index, message in enumerate(messages, start=1):
        lines.extend(
            [
                f"## Message {index}",
                "",
                f"- Tick: {message.get('X-Sim-Tick', '')}",
                f"- Direction: {message.get('X-Sim-Direction', '')}",
                f"- Persona: {message.get('X-Sim-Persona', '')}",
                f"- Trace-Id: {message.get('X-Sim-Trace-Id', '')}",
                f"- From: {message.get('From', '')}",
                f"- To: {message.get('To', '')}",
                f"- Subject: {message.get('Subject', '')}",
                "",
                "```text",
                _extract_body(message).strip(),
                "```",
                "",
            ]
        )
    transcript = "\n".join(lines).rstrip() + "\n"
    if transcript_path is not None:
        transcript_path.parent.mkdir(parents=True, exist_ok=True)
        transcript_path.write_text(transcript, encoding="utf-8")
    return transcript


def _stamp_sim_headers(message: EmailMessage, meta: SimMessageMeta) -> None:
    for name, value in (
        ("X-Sim-Tick", str(meta.tick)),
        ("X-Sim-Direction", meta.direction),
        ("X-Sim-Persona", meta.persona),
        ("X-Sim-Trace-Id", meta.trace_id),
    ):
        if name in message:
            message.replace_header(name, value)
        else:
            message[name] = value


def _recipient_addresses(message: EmailMessage) -> tuple[str, ...]:
    header_values = [
        value for name in ("to", "cc", "bcc") for value in message.get_all(name, [])
    ]
    addresses = {
        _normalize_address(address)
        for _display_name, address in getaddresses(header_values)
        if address
    }
    return tuple(sorted(addresses))


def _normalize_address(address: str) -> str:
    return parseaddr(address)[1].strip().lower()


def _extract_body(message: EmailMessage) -> str:
    if hasattr(message, "get_body"):
        plain = message.get_body(preferencelist=("plain",))
        if plain is not None:
            return plain.get_content()
        html = message.get_body(preferencelist=("html",))
        if html is not None:
            return _html_to_text(html.get_content())
    else:
        for part in message.walk() if message.is_multipart() else (message,):
            if part.get_content_type() == "text/plain":
                return _compat_payload_text(part)
        for part in message.walk() if message.is_multipart() else (message,):
            if part.get_content_type() == "text/html":
                return _html_to_text(_compat_payload_text(part))

    if message.get_content_maintype() == "text":
        return (
            message.get_content()
            if hasattr(message, "get_content")
            else _compat_payload_text(message)
        )
    return ""


def _compat_payload_text(message) -> str:
    payload = message.get_payload(decode=True)
    charset = message.get_content_charset() or "utf-8"
    if isinstance(payload, bytes):
        return payload.decode(charset, errors="replace")
    if isinstance(payload, str):
        return payload
    return ""


def _html_to_text(html: str) -> str:
    return html_to_visible_text(html)
